# Generated by Django 6.0.3 on 2026-04-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_caregiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinelog',
            name='alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medicinelog',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
